### ISSUE TITLE
"latest" is invalid go.mod syntax

### ISSUE THREAD

**Issue by thisguycodes** [snabb/tcxpgrp#1]
```
go: github.com/snabb/tcxpgrp@v1.0.2: parsing go.mod: go.mod:3: invalid module version "latest": version must be of the form v1.2.3
```

**Comment by snabb** [comment]
Hi,

Thanks for your report. How do you get this error message? I do not get errors with "latest" syntax when using Go 1.12.x series.

I decided to use "latest" until the Go developers make golang.org/x/sys properly versioned (as the automatically generated git versions create quite a mess when several modules depend on golang.org/x/sys). But I am happy to change it if it does not work under some circumstances.

**Comment by pupper68k** [comment]
Hello, I have gotten this error on go 1.14.4
```
~/go/src/gitlab.com/whom/shs on  dev! ⌚ 23:35:24
$ go install ./cmd/test_shell.go
go: finding module for package github.com/snabb/tcxpgrp
go: found github.com/snabb/tcxpgrp in github.com/snabb/tcxpgrp v1.0.2
go: gitlab.com/whom/shs/stdlib imports
        github.com/snabb/tcxpgrp: github.com/snabb/tcxpgrp@v1.0.2: parsing go.mod: go.mod:3: require golang.org/x/sys: version "latest" invalid: must be of the form v1.2.3

~/go/src/gitlab.com/whom/shs on  dev! ⌚ 23:37:35
$ go version
go version go1.14.4 linux/amd64

```

**Comment by snabb** [comment]
Thanks. Fixed.
